version: "2"
services:
  # redis:
  #   build: ./redis/
  #   restart: always
  #   container_name: mac-redis 

  identity:
    build: ~/Documents/CnblogsProjects/identity/src/CNBlogs.Identity.Web/
    restart: always
    volumes:
      - ~/Documents/CnblogsProjects/identity/src/CNBlogs.Identity.Web/bin/Debug/netcoreapp1.1/publish:/app
    # links:
    #   - service.ucenter.cnblogs.com
    extra_hosts:
      - "dbserver:192.168.199.143"
      - "memcached:192.168.199.143"
      - "redis:192.168.199.143"
    container_name: identity
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "10"

  blog-admin:
    build: ~/Documents/CnblogsProjects/BlogServer/MigrateToCore/src/BlogServerAdmin.Web
    restart: always
    volumes:
      - ~/Documents/CnblogsProjects/BlogServer/MigrateToCore/src/BlogServerAdmin.Web/bin/Debug/netcoreapp2.0/publish:/app
    links:
      - "ucenter:api.ucenter.cnblogs.com"
    extra_hosts:
      - "dbserver:192.168.199.143"
      - "ucenter.cnblogs.com:192.168.199.143"
      - "service.ucenter.cnblogs.com:192.168.199.143"
      - "service.msg.cnblogs.com:192.168.199.143"
      - "blog.wcf.cnblogs.com:192.168.199.143"
      - "news.wcf.cnblogs.com:192.168.199.143"
      - "kb.wcf.cnblogs.com:192.168.199.143"
      - "job.cnblogs.com:192.168.199.143"
      - "api.ing.cnblogs.com:192.168.199.143"
      - "memcached:192.168.199.143"
      - "redis:192.168.199.143"
      - "markdown.cnblogs.com:192.168.199.143"
      - "api.upload.cnblogs.com:192.168.199.143"
    container_name: blog-admin
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "10"

  uchome:
    build: ~/Documents/CnblogsProjects/UcHome/Migrate2Core/src/Cnblogs.UcHome.Web
    restart: always
    volumes:
      - ~/Documents/CnblogsProjects/UcHome/Migrate2Core/src/Cnblogs.UcHome.Web/bin/Debug/netcoreapp2.0/publish:/app
    links:
      - "ucenter:api.ucenter.cnblogs.com"
      - "job:api.job.cnblogs.com"
    extra_hosts:
      - "dbserver:192.168.199.143"
      - "ucenter.cnblogs.com:192.168.199.143"
      - "service.ucenter.cnblogs.com:192.168.199.143"
      - "service.msg.cnblogs.com:192.168.199.143"
      - "blog.wcf.cnblogs.com:192.168.199.143"
      - "news.wcf.cnblogs.com:192.168.199.143"
      - "kb.wcf.cnblogs.com:192.168.199.143"
      - "job.cnblogs.com:192.168.199.143"
      - "api.ing.cnblogs.com:192.168.199.143"
      - "memcached:192.168.199.143"
      - "redis:192.168.199.143"
    container_name: uchome
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "10"

  ucenter:
    build: ~/Documents/CnblogsProjects/CNBlogsUCenter/core/src/Cnblogs.UCenter.WebAPI
    restart: always
    volumes:
      - ~/Documents/CnblogsProjects/CNBlogsUCenter/core/src/Cnblogs.UCenter.WebAPI/bin/Debug/netcoreapp2.0/publish:/app
    links:
      - "cache-server: cache.cnblogs.com"
    #   - redis
    extra_hosts:
      - "dbserver:192.168.199.143"
      - "memcached:192.168.199.143"
      - "redis:192.168.199.143"
    container_name: ucenter

  job:
    build: ~/Documents/CnblogsProjects/CNBlogsJob/src/CNBlogs.Job.WebApi
    restart: always
    volumes:
      - ~/Documents/CnblogsProjects/CNBlogsJob/src/CNBlogs.Job.WebApi/bin/Debug/netcoreapp2.0/publish:/app
    extra_hosts:
      - "dbserver:192.168.199.143"
      - "memcached:192.168.199.143"
      - "redis:192.168.199.143"
    container_name: job

  upload:
    build: ~/Documents/CnblogsProjects/CNBlogsUpload/src/CNBlogs.Upload.Web
    restart: always
    volumes:
      - ~/Documents/CnblogsProjects/CNBlogsUpload/src/CNBlogs.Upload.Web/bin/Debug/netcoreapp2.0/publish:/app
    links:
      - "ucenter:api.ucenter.cnblogs.com"
    extra_hosts:
      - "dbserver:192.168.199.143"
      - "memcached:192.168.199.143"
      - "redis:192.168.199.143"
    container_name: upload

  cache-server:
    image: jamesdbloom/mockserver
    restart: always
    container_name: cache-server

  nginx-host:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    links:
      - identity
      - blog-admin
      - uchome
      - ucenter
      - job
      # - redis
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - /Users/Feng/Documents/CnblogsProjects/WebCommon:/www/data
    container_name: nginx-host
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "10"

